### ISSUE TITLE
Problem about NoteType enum in released appveyor binaries (v0.1.5-5, v0.1.5-12)

### ISSUE THREAD

**Issue by HolySkyMin** [hozuki/MilliSim#8]
In these versions, there seems no NoteType.Invalid (which is 0 in value): so NoteType.Tap becomes 0 in value. As a result, when you build a plugin using NoteType and run it in released binaries, they are being converted like this:

NoteType.Tap (1 in repo source version) -> NoteType.Flick (1 in released binaries)
NoteType.Flick (2 in repo source version) -> NoteType.Hold (2 in released binaries)
NoteType.Hold (3 in repo source version) -> NoteType.Slide (3 in released binaries)
NoteType.Slide (4 in repo source version) -> 4
(No problem for NoteType.Special and after since it is pre-defined as 100)

So new binary release is required I think.

**Comment by hozuki** [comment]
Hmm... `master` branch is now the most recent edit (0.2.x, WIP), not the most recent release.

CLR will check the correct version for reference assemblies. So if you compile your code using the lastest `master` (not referencing the compiled assemblies), and run your plugin *directly* using the old version, CLR will throw a `FileNotFoundException` ([here](https://docs.microsoft.com/en-us/dotnet/framework/deployment/how-the-runtime-locates-assemblies)).

I thought that tags are special branches, but they aren't. Then I created a new branch [rel-v0.1](https://github.com/hozuki/MilliSim/tree/rel-v0.1). Developments of specific versions should be based on those branches, rather than `master`. 

The workflow looks more like GitLab Workflow (`master`: development, `release-`: production) now. I will update contributing document to adhere. Thank you.

**Comment by HolySkyMin** [comment]
Thanks a lot. Divided branch (for plugin builder) will help developers a lot.
